name: "lua CI workflow"


on:
  push:
    branches: [ test ]
  # schedule:
  #     - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month 


jobs:

  lua-ubuntu-latest-job:
    name: "docker ubuntu latest"
    env:
      distribution: "ubuntu"
      version: "latest"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Luver
        uses: ./
        with:
          default: 5.4.3
          lua_versions: 5.1.5 5.4.3
          luajit_versions: 5.1.5:2.1.0-beta3
          luarocks_versions: 5.1.5:3.7.0 5.4.3:3.8.0
      - name: Validate
        shell: bash
        run: |
          set -euo pipefail
          test "$(luver current lua)" = "5.4.3"
          luver use 5.1.5
          test "$(luver current lua)" = "5.1.5"
          test "$(luver current luajit)" = "2.1.0-beta3"
          test "$(luver current luarocks)" = "3.7.0"
          luver use 5.4.3
          test "$(luver current lua)" = "5.4.3"
          test "$(luver current luarocks)" = "3.8.0"
    - name: "Test"
      run: lua -e 'print("hello world lua")'  